apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-server
  labels:
    app: pass-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pass-server
  template:
    metadata:
      labels:
        app: pass-server
    spec:
      containers:
        - name: pass-server
          image: skirkyn/skirkyn:pass_server
          imagePullPolicy: Always
          ports:
           - containerPort: 5000
             hostPort: 5000
             name: flask


---

apiVersion: v1
kind: Service
metadata:
  name: pass-server-service
spec:
  type: ClusterIP
  selector:
    app: pass-server
  ports:
    - port: 80
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: pass-server-lb
spec:
  selector:
    app: pass-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 36000